var monsterData = [
    { 'id': '0', 'attribute': '', 'race': '', 'star': '', 'recover': [], 'skill': [] },
    { 'id': '1', 'attribute': '水', 'race': '人類', 'star': '2', 'skill': ['引爆', '木符石引爆', '直傷', ] },
    { 'id': '2', 'attribute': '水', 'race': '人類', 'star': '3', 'skill': ['引爆', '木符石引爆', '直傷', ] },
    { 'id': '3', 'attribute': '水', 'race': '人類', 'star': '4', 'skill': ['引爆', '木符石引爆', '直傷', ] },
    { 'id': '4', 'attribute': '水', 'race': '人類', 'star': '5', 'skill': ['引爆', '木符石引爆', '直傷', ] },
    { 'id': '5', 'attribute': '火', 'race': '人類', 'star': '2', 'skill': ['引爆', '水符石引爆', '直傷', ] },
    { 'id': '6', 'attribute': '火', 'race': '人類', 'star': '3', 'skill': ['引爆', '水符石引爆', '直傷', ] },
    { 'id': '7', 'attribute': '火', 'race': '人類', 'star': '4', 'skill': ['引爆', '水符石引爆', '直傷', ] },
    { 'id': '8', 'attribute': '火', 'race': '人類', 'star': '5', 'skill': ['引爆', '水符石引爆', '直傷', ] },
    { 'id': '9', 'attribute': '木', 'race': '人類', 'star': '2', 'skill': ['引爆', '火符石引爆', '直傷', ] },
    { 'id': '10', 'attribute': '木', 'race': '人類', 'star': '3', 'skill': ['引爆', '火符石引爆', '直傷', ] },
    { 'id': '11', 'attribute': '木', 'race': '人類', 'star': '4', 'skill': ['引爆', '火符石引爆', '直傷', ] },
    { 'id': '12', 'attribute': '木', 'race': '人類', 'star': '5', 'skill': ['引爆', '火符石引爆', '直傷', ] },
    { 'id': '13', 'attribute': '光', 'race': '人類', 'star': '2', 'skill': ['引爆', '暗符石引爆', '直傷', ] },
    { 'id': '14', 'attribute': '光', 'race': '人類', 'star': '3', 'skill': ['引爆', '暗符石引爆', '直傷', ] },
    { 'id': '15', 'attribute': '光', 'race': '人類', 'star': '4', 'skill': ['引爆', '暗符石引爆', '直傷', ] },
    { 'id': '16', 'attribute': '光', 'race': '人類', 'star': '5', 'skill': ['引爆', '暗符石引爆', '直傷', ] },
    { 'id': '17', 'attribute': '暗', 'race': '人類', 'star': '2', 'skill': ['引爆', '光符石引爆', '直傷', ] },
    { 'id': '18', 'attribute': '暗', 'race': '人類', 'star': '3', 'skill': ['引爆', '光符石引爆', '直傷', ] },
    { 'id': '19', 'attribute': '暗', 'race': '人類', 'star': '4', 'skill': ['引爆', '光符石引爆', '直傷', ] },
    { 'id': '20', 'attribute': '暗', 'race': '人類', 'star': '5', 'skill': ['引爆', '光符石引爆', '直傷', ] },
    { 'id': '21', 'attribute': '水', 'race': '龍類', 'star': '2', 'skill': ['符石轉水', '心轉其他', ] },
    { 'id': '22', 'attribute': '水', 'race': '龍類', 'star': '3', 'skill': ['符石轉水', '心轉其他', ] },
    { 'id': '23', 'attribute': '水', 'race': '龍類', 'star': '4', 'skill': ['符石轉水', '心轉其他', ] },
    { 'id': '24', 'attribute': '水', 'race': '龍類', 'star': '5', 'skill': ['符石轉水', '心轉其他', ] },
    { 'id': '25', 'attribute': '火', 'race': '獸類', 'star': '2', 'skill': ['符石轉心', '木轉其他', ] },
    { 'id': '26', 'attribute': '火', 'race': '獸類', 'star': '3', 'skill': ['符石轉心', '木轉其他', ] },
    { 'id': '27', 'attribute': '火', 'race': '獸類', 'star': '4', 'skill': ['符石轉心', '木轉其他', ] },
    { 'id': '28', 'attribute': '火', 'race': '獸類', 'star': '5', 'skill': ['符石轉心', '木轉其他', ] },
    { 'id': '29', 'attribute': '木', 'race': '獸類', 'star': '2', 'skill': ['減傷', ] },
    { 'id': '30', 'attribute': '木', 'race': '獸類', 'star': '3', 'skill': ['減傷', ] },
    { 'id': '31', 'attribute': '木', 'race': '獸類', 'star': '4', 'skill': ['減傷', ] },
    { 'id': '32', 'attribute': '木', 'race': '獸類', 'star': '5', 'skill': ['減傷', ] },
    { 'id': '33', 'attribute': '光', 'race': '獸類', 'star': '2', 'skill': ['破防', ] },
    { 'id': '34', 'attribute': '光', 'race': '獸類', 'star': '3', 'skill': ['破防', ] },
    { 'id': '35', 'attribute': '光', 'race': '獸類', 'star': '4', 'skill': ['破防', ] },
    { 'id': '36', 'attribute': '光', 'race': '獸類', 'star': '5', 'skill': ['破防', ] },
    { 'id': '37', 'attribute': '暗', 'race': '獸類', 'star': '2', 'skill': ['符石轉心', '光轉其他', ] },
    { 'id': '38', 'attribute': '暗', 'race': '獸類', 'star': '3', 'skill': ['符石轉心', '光轉其他', ] },
    { 'id': '39', 'attribute': '暗', 'race': '獸類', 'star': '4', 'skill': ['符石轉心', '光轉其他', ] },
    { 'id': '40', 'attribute': '暗', 'race': '獸類', 'star': '5', 'skill': ['符石轉心', '光轉其他', ] }, { 'id': '41', 'attribute': '水', 'race': '龍類', 'star': '3', 'recover': ['CD'], 'skill': ['直傷', ] },
    { 'id': '42', 'attribute': '水', 'race': '龍類', 'star': '4', 'skill': ['直傷', ] },
    { 'id': '43', 'attribute': '水', 'race': '龍類', 'star': '5', 'skill': ['直傷', ] },
    { 'id': '44', 'attribute': '火', 'race': '龍類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '45', 'attribute': '火', 'race': '龍類', 'star': '4', 'skill': ['直傷', ] },
    { 'id': '46', 'attribute': '火', 'race': '龍類', 'star': '5', 'skill': ['直傷', ] },
    { 'id': '47', 'attribute': '木', 'race': '龍類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '48', 'attribute': '木', 'race': '龍類', 'star': '4', 'skill': ['直傷', ] },
    { 'id': '49', 'attribute': '木', 'race': '龍類', 'star': '5', 'skill': ['直傷', ] },
    { 'id': '50', 'attribute': '光', 'race': '龍類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '51', 'attribute': '光', 'race': '龍類', 'star': '4', 'skill': ['直傷', ] },
    { 'id': '52', 'attribute': '光', 'race': '龍類', 'star': '5', 'skill': ['直傷', ] },
    { 'id': '53', 'attribute': '暗', 'race': '龍類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '54', 'attribute': '暗', 'race': '龍類', 'star': '4', 'skill': ['直傷', ] },
    { 'id': '55', 'attribute': '暗', 'race': '龍類', 'star': '5', 'skill': ['直傷', ] },
    { 'id': '56', 'attribute': '水', 'race': '妖精類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '57', 'attribute': '水', 'race': '妖精類', 'star': '3', 'skill': ['符石轉水', '心轉其他', ] },
    { 'id': '58', 'attribute': '火', 'race': '妖精類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '59', 'attribute': '火', 'race': '妖精類', 'star': '3', 'skill': ['符石轉火', '心轉其他', ] },
    { 'id': '60', 'attribute': '木', 'race': '妖精類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '61', 'attribute': '木', 'race': '妖精類', 'star': '3', 'skill': ['符石轉木', '心轉其他', ] },
    { 'id': '62', 'attribute': '光', 'race': '妖精類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '63', 'attribute': '光', 'race': '妖精類', 'star': '3', 'skill': ['符石轉光', '心轉其他', ] },
    { 'id': '64', 'attribute': '暗', 'race': '妖精類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '65', 'attribute': '暗', 'race': '妖精類', 'star': '3', 'skill': ['符石轉暗', '心轉其他', ] },
    { 'id': '66', 'attribute': '水', 'race': '妖精類', 'star': '2', 'skill': ['回血', ] },
    { 'id': '67', 'attribute': '水', 'race': '妖精類', 'star': '3', 'skill': ['回血', ] },
    { 'id': '68', 'attribute': '火', 'race': '妖精類', 'star': '2', 'skill': ['回血', ] },
    { 'id': '69', 'attribute': '火', 'race': '妖精類', 'star': '3', 'skill': ['回血', ] },
    { 'id': '70', 'attribute': '木', 'race': '妖精類', 'star': '2', 'skill': ['回血', ] },
    { 'id': '71', 'attribute': '木', 'race': '妖精類', 'star': '3', 'skill': ['回血', ] },
    { 'id': '72', 'attribute': '光', 'race': '妖精類', 'star': '2', 'skill': ['回血', ] },
    { 'id': '73', 'attribute': '光', 'race': '妖精類', 'star': '3', 'skill': ['回血', ] },
    { 'id': '74', 'attribute': '暗', 'race': '妖精類', 'star': '2', 'skill': ['回血', ] },
    { 'id': '75', 'attribute': '暗', 'race': '妖精類', 'star': '3', 'skill': ['回血', ] },
    { 'id': '76', 'attribute': '水', 'race': '龍類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '77', 'attribute': '水', 'race': '龍類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '78', 'attribute': '火', 'race': '龍類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '79', 'attribute': '火', 'race': '龍類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '80', 'attribute': '木', 'race': '龍類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '81', 'attribute': '木', 'race': '龍類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '82', 'attribute': '光', 'race': '龍類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '83', 'attribute': '光', 'race': '龍類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '84', 'attribute': '暗', 'race': '龍類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '85', 'attribute': '暗', 'race': '龍類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '86', 'attribute': '水', 'race': '人類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '87', 'attribute': '水', 'race': '人類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '88', 'attribute': '火', 'race': '人類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '89', 'attribute': '火', 'race': '人類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '90', 'attribute': '木', 'race': '人類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '91', 'attribute': '木', 'race': '人類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '92', 'attribute': '光', 'race': '人類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '93', 'attribute': '光', 'race': '人類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '94', 'attribute': '暗', 'race': '人類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '95', 'attribute': '暗', 'race': '人類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '96', 'attribute': '水', 'race': '妖精類', 'star': '1', 'skill': ['直傷', ] },
    { 'id': '97', 'attribute': '水', 'race': '妖精類', 'star': '2', 'skill': ['符石轉心', '火轉其他', ] },
    { 'id': '98', 'attribute': '火', 'race': '妖精類', 'star': '1', 'skill': ['直傷', ] },
    { 'id': '99', 'attribute': '火', 'race': '妖精類', 'star': '2', 'skill': ['符石轉心', '木轉其他', ] },
    { 'id': '100', 'attribute': '木', 'race': '妖精類', 'star': '1', 'skill': ['直傷', ] },
    { 'id': '101', 'attribute': '木', 'race': '妖精類', 'star': '2', 'skill': ['符石轉心', '水轉其他', ] },
    { 'id': '102', 'attribute': '光', 'race': '妖精類', 'star': '1', 'skill': ['直傷', ] },
    { 'id': '103', 'attribute': '光', 'race': '妖精類', 'star': '2', 'skill': ['符石轉心', '暗轉其他', ] },
    { 'id': '104', 'attribute': '暗', 'race': '妖精類', 'star': '1', 'skill': ['直傷', ] },
    { 'id': '105', 'attribute': '暗', 'race': '妖精類', 'star': '2', 'skill': ['符石轉心', '光轉其他', ] },
    { 'id': '106', 'attribute': '水', 'race': '獸類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '107', 'attribute': '水', 'race': '獸類', 'star': '3', 'skill': ['破防', ] },
    { 'id': '108', 'attribute': '火', 'race': '獸類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '109', 'attribute': '火', 'race': '獸類', 'star': '3', 'skill': ['破防', ] },
    { 'id': '110', 'attribute': '木', 'race': '獸類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '111', 'attribute': '木', 'race': '獸類', 'star': '3', 'skill': ['破防', ] },
    { 'id': '112', 'attribute': '光', 'race': '獸類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '113', 'attribute': '光', 'race': '獸類', 'star': '3', 'skill': ['破防', ] },
    { 'id': '114', 'attribute': '暗', 'race': '獸類', 'star': '2', 'skill': ['直傷', ] },
    { 'id': '115', 'attribute': '暗', 'race': '獸類', 'star': '3', 'skill': ['破防', ] },
    { 'id': '116', 'attribute': '水', 'race': '神族', 'star': '3', 'skill': ['無法行動', '敵方轉屬', ] },
    { 'id': '117', 'attribute': '水', 'race': '神族', 'star': '4', 'skill': ['無法行動', '敵方轉屬', ] },
    { 'id': '118', 'attribute': '水', 'race': '神族', 'star': '5', 'skill': ['無法行動', '敵方轉屬', ] },
    { 'id': '119', 'attribute': '火', 'race': '神族', 'star': '3', 'skill': ['排珠', ] },
    { 'id': '120', 'attribute': '火', 'race': '神族', 'star': '4', 'skill': ['排珠', ] },
    { 'id': '121', 'attribute': '火', 'race': '神族', 'star': '5', 'skill': ['排珠', ] },
    { 'id': '122', 'attribute': '木', 'race': '神族', 'star': '3', 'skill': ['回血', ] },
    { 'id': '123', 'attribute': '木', 'race': '神族', 'star': '4', 'skill': ['回血', ] },
    { 'id': '124', 'attribute': '木', 'race': '神族', 'star': '5', 'skill': ['回血', ] },
    { 'id': '125', 'attribute': '光', 'race': '神族', 'star': '3', 'skill': ['回血', ] },
    { 'id': '126', 'attribute': '光', 'race': '神族', 'star': '4', 'skill': ['回血', ] },
    { 'id': '127', 'attribute': '光', 'race': '神族', 'star': '5', 'skill': ['回血', ] },
    { 'id': '128', 'attribute': '暗', 'race': '神族', 'star': '3', 'skill': [] },
    { 'id': '129', 'attribute': '暗', 'race': '神族', 'star': '4', 'skill': [] },
    { 'id': '130', 'attribute': '暗', 'race': '神族', 'star': '5', 'skill': [] },
    { 'id': '131', 'attribute': '水', 'race': '人類', 'star': '3', 'skill': ['減傷', ] },
    { 'id': '132', 'attribute': '水', 'race': '人類', 'star': '4', 'skill': ['減傷', ] },
    { 'id': '133', 'attribute': '水', 'race': '人類', 'star': '5', 'skill': ['減傷', ] },
    { 'id': '134', 'attribute': '火', 'race': '人類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '135', 'attribute': '火', 'race': '人類', 'star': '4', 'skill': ['直傷', ] },
    { 'id': '136', 'attribute': '火', 'race': '人類', 'star': '5', 'skill': ['直傷', ] },
    { 'id': '137', 'attribute': '木', 'race': '人類', 'star': '3', 'skill': ['直傷', ] },
    { 'id': '138', 'attribute': '木', 'race': '人類', 'star': '4', 'skill': ['直傷', ] },
    { 'id': '139', 'attribute': '木', 'race': '人類', 'star': '5', 'skill': ['直傷', ] },
    { 'id': '140', 'attribute': '光', 'race': '人類', 'star': '3', 'skill': ['回血', ] },
    { 'id': '141', 'attribute': '光', 'race': '人類', 'star': '4', 'skill': ['回血', ] },
    { 'id': '142', 'attribute': '光', 'race': '人類', 'star': '5', 'skill': ['回血', ] },
    { 'id': '143', 'attribute': '暗', 'race': '人類', 'star': '3', 'skill': [] },
    { 'id': '144', 'attribute': '暗', 'race': '人類', 'star': '4', 'skill': [] },
    { 'id': '145', 'attribute': '暗', 'race': '人類', 'star': '5', 'skill': [] },
];
var obj = monsterData;
$(".custom-btn").click(() => {
    $(".custom-btn").css("background-color", "red");
    console.log("???")
});

console.log(obj);
// console.log(obj.pokemon);